### GET ALL ITEMS
GET  http://127.0.0.1:5000/items HTTP/1.1


### GET SINGLE ITEM
GET  http://127.0.0.1:5000/items/1 HTTP/1.1

### POST ITEM
POST  http://127.0.0.1:5000/items HTTP/1.1
Content-Type: application/json

{
    "name":"New Item"
}