### GET ALL ITEMS
GET  http://127.0.0.1:5000/items HTTP/1.1


### GET SINGLE ITEM
GET  http://127.0.0.1:5000/items/1 HTTP/1.1

### POST ITEM
POST  http://127.0.0.1:5000/items HTTP/1.1
Content-Type: application/json

{
    "name": "New Item",
    "description": "Description",
    "price": 1024,
    "image": "image.jpg"
}

### DELETE SINGLE ITEM
DELETE  http://127.0.0.1:5000/items/1 HTTP/1.1


### UPDATE SINGLE ITEM
PUT  http://127.0.0.1:5000/items/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item",
    "description": "Description",
    "price": 1024,
    "image": "image.jpg"
}
